Koala.languages["pt"] = {
    "Bold": "Negrito",
    "Italic": "Itálico",
    "Underline": "Sublinhado",
    "Ordered list": "Lista ordenada",
    "Unordered list": "Lista",
    "Block Style": "Estilo de Bloco",
    "Normal": "Normal",
    "Heading 1": "Cabeçalho 1",
    "Heading 2": "Cabeçalho 2",
    "Heading 3": "Cabeçalho 3",
    "Heading 4": "Cabeçalho 4",
    "Align": "Alinhar",
    "Left": "Esquerda",
    "Center": "Centro",
    "Right": "Direita",
    "Justify": "Justificar",
    "Undo": "Desfazer",
    "Redo": "Refazer",
    "Insert image": "Inserir imagem",
    "Insert link": "Inserir ligação",
    "Remove link": "Remover ligação",
    "View code": "Ver código",
    "Image URL:": "URL da imagem:",
    "Link URL:": "URL da ligação:",
    "Drop file": "Largue o ficheiro",
    "or click": "ou clique"
};