Koala.languages["pt_pt"] = {
    "Bold": "Negrito",
    "Italic": "Itálico",
    "Underline": "Sublinhado",
    "Ordered list": "Lista ordenada",
    "Unordered list": "Lista",
    "Block Style": "Estilo de Bloco",
    "Normal": "Normal",
    "Heading 1": "Cabeçalho 1",
    "Align": "Alinhar",
    "Left": "Esquerda",
    "Center": "Centro",
    "Right": "Direita",
    "Justify": "Justificar",
    "Undo": "Desfazer",
    "Redo": "Refazer",
    "Insert image": "Inserir imagem",
    "Link": "Ligação",
    "Remove link": "Remover ligação",
    "View code": "Ver código",
    "Image URL:": "URL da imagem:",
    "Link URL:": "URL da ligação:",
    "Do you really want to remove this image?": "Quer mesmo remover esta imagem?"
};